const portfolioItems = [
    {
        title: 'A visual analysis of UK number 1s',
        imgsrc: 'img/visual-analysis-uk-number1s.png',
        filters: ['example', 'core-content', 'webdevelopment', 'webdesign', 'misc'],
        portfolioLink: 'UK-number-1s.html',
        description: ,
        projectLink ,
        relatedImg: ,
        projectImg: ,
        related1img ,
        related1link ,
        related1alt ,
        related2img ,
        related2link ,
        related2alt ,
        projectPageName: ,
    },
    {
        title: ,
        imgsrc: ,
        filters: [],
        portfolioLink: ,
        description:,
        projectLink ,
        relatedImg: ,
        projectImg: ,
        related1img ,
        related1link ,
        related1alt ,
        related2img ,
        related2link ,
        related2alt ,
        projectPageName: ,
    },
    {
        title: ,
        imgsrc: ,
        filters: [],
        portfolioLink: ,
        description:,
        projectLink ,
        relatedImg: ,
        projectImg: ,
        related1img ,
        related1link ,
        related1alt ,
        related2img ,
        related2link ,
        related2alt ,
        projectPageName: ,
    },
    {
        title: ,
        imgsrc: ,
        filters: [],
        portfolioLink: ,
        description:,
        projectLink ,
        relatedImg: ,
        projectImg: ,
        related1img ,
        related1link ,
        related1alt ,
        related2img ,
        related2link ,
        related2alt ,
        projectPageName: ,
    },
    {
        title: ,
        imgsrc: ,
        filters: [],
        portfolioLink: ,
        description:,
        projectLink ,
        relatedImg: ,
        projectImg: ,
        related1img ,
        related1link ,
        related1alt ,
        related2img ,
        related2link ,
        related2alt ,
        projectPageName: ,
    },
    {
        title: ,
        imgsrc: ,
        filters: [],
        portfolioLink: ,
        description:,
        projectLink ,
        relatedImg: ,
        projectImg: ,
        related1img ,
        related1link ,
        related1alt ,
        related2img ,
        related2link ,
        related2alt ,
        projectPageName: ,
    },
    {
        title: ,
        imgsrc: ,
        filters: [],
        portfolioLink: ,
        description:,
        projectLink ,
        relatedImg: ,
        projectImg: ,
        related1img ,
        related1link ,
        related1alt ,
        related2img ,
        related2link ,
        related2alt ,
        projectPageName: ,
    },
    {
        title: ,
        imgsrc: ,
        filters: [],
        portfolioLink: ,
        description:,
        projectLink ,
        relatedImg: ,
        projectImg: ,
        related1img ,
        related1link ,
        related1alt ,
        related2img ,
        related2link ,
        related2alt ,
        projectPageName: ,
    },
    {
        title: ,
        imgsrc: ,
        filters: [],
        portfolioLink: ,
        description:,
        projectLink ,
        relatedImg: ,
        projectImg: ,
        related1img ,
        related1link ,
        related1alt ,
        related2img ,
        related2link ,
        related2alt ,
        projectPageName: ,
    },
]

const testimonials = [
    {
        testimonial: ,
        speaker: ,
        img: ,
        link: ,
        speakerRole: ,
    }
]

export default portfolioItems;